name: redis_house
description: Redis House.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  built_value: ^7.1.0
  built_collection: ^4.3.2
  fluro: ^1.7.8
  after_init: ^0.1.2
  bot_toast: ^3.0.5
  pigment: 1.0.3
  logger: ^0.9.4
  # 错误捕获上报等操作
  catcher: ^0.3.22
  uuid: ^2.2.2
  flutter_easyloading: ^2.2.1
  # 需要改
  # split_view: ^1.0.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  sembast: ^2.4.8
  # sqflite: ^1.3.2+1
  # sqflite_common_ffi: ^1.1.1
  # flutter_simple_treeview: ^2.0.2
  getwidget: ^1.2.4
  ndialog: ^3.1.0
  extended_tabs: ^1.0.1
  fl_chart: ^0.12.1
  menu_button: ^1.2.1
  sprintf: ^5.0.0

dependency_overrides:
  analyzer: ^0.41.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.7
  built_value_generator: ^7.1.0
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/tmp/

flutter_intl:
  enabled: true
