name: go-flutter

on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v0.4
        with:
          version: 1.22.4

      - name: Print flutter SDK version
        run: flutter --version
     
      - name: Install graphic lib
        run: |
          sudo apt install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
          sudo apt-get install -y mesa-common-dev
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
       
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.6
          stable: true
    
      - name: Print go env and version
        run: |
          go env -w GO111MODULE=on
          go env
          go version
          
      - name: Install dependencies
        run: flutter pub get
      
      - name: Install hover
        run: go get -u -a github.com/go-flutter-desktop/hover
    
      - name: build linux
        run: |
          hover build linux-appimage

  build-darwin:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v0.4
        with:
          version: 1.22.4

      - name: Print flutter SDK version
        run: flutter --version

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.6
          stable: true
    
      - name: Print go env and version
        run: |
          go env -w GO111MODULE=on
          go env
          go version
          
      - name: Install dependencies
        run: flutter pub get
      
      - name: Install hover
        run: go get -u -a github.com/go-flutter-desktop/hover
    
      - name: build darwin
        run: |
          hover build darwin-bundle

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v0.4
        with:
          version: 1.22.4

      - name: Print flutter SDK version
        run: flutter --version

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.6
          stable: true
    
      - name: Print go env and version
        run: |
          go env -w GO111MODULE=on
          go env
          go version
          
      - name: Install dependencies
        run: flutter pub get
      
      - name: Install hover
        run: go get -u -a github.com/go-flutter-desktop/hover
    
      - name: build windows
        run: |
          hover build windows-msi