name: go-flutter

on:
  push:
    branches: [ master ]

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v0.4
        with:
          version: 1.22.4

      - name: Print flutter SDK version
        run: flutter --version
     
      - name: Install graphic lib
        run: |
          sudo apt install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
          sudo apt-get install -y mesa-common-dev
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
       
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.6
          stable: true
    
      - name: Print go env and version
        run: |
          go env -w GO111MODULE=on
          go env
          go version
          
      - name: Install dependencies
        run: flutter pub get
      
      - name: Install hover
        run: go get -u -a github.com/go-flutter-desktop/hover
    
      - name: Install appimagetool
        run: |
          sudo apt install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot
          sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
          sudo chmod +x /usr/local/bin/appimagetool

      - name: build linux
        run: |
          hover build linux-appimage
          sudo apt install -y tree
          tree ./go/build/outputs/

      - name: 'Upload appimage'
        uses: actions/upload-artifact@v2
        with:
          name: Redis_House-1.0.0-x86_64.AppImage
          path: ./go/build/outputs/linux-appimage-release/Redis_House-1.0.0-x86_64.AppImage
          retention-days: 5

  build-darwin:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v0.4
        with:
          version: 1.22.4

      - name: Print flutter SDK version
        run: flutter --version

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.6
          stable: true
    
      - name: Print go env and version
        run: |
          go env -w GO111MODULE=on
          go env
          go version
          
      - name: Install dependencies
        run: flutter pub get
      
      - name: Install hover
        run: go get -u -a github.com/go-flutter-desktop/hover
    
      - name: build darwin
        run: |
          hover build darwin-bundle
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: Redis\ House\ 1.0.0.app
          path: ./go/build/outputs/darwin-bundle-release/Redis\ House\ 1.0.0.app
          retention-days: 5


  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v0.4
        with:
          version: 1.22.4

      - name: Print flutter SDK version
        run: flutter --version

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.6
          stable: true
    
      - name: Print go env and version
        run: |
          go env -w GO111MODULE=on
          go env
          go version
          
      - name: Install dependencies
        run: flutter pub get
      
      - name: Install hover
        run: go get -u -a github.com/go-flutter-desktop/hover

      - name: Download wix311
        run: certutil.exe -urlcache -split -f https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe wix311.exe
      
      - name: Install wix311
        run: ｜
          wix311.exe /install /quiet /norestart

      - name: build windows
        run: |
          hover build windows-msi


  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: ['build-linux', 'build-darwin']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Redis_House-1.0.0-x86_64.AppImage
          path: ./
       
      - name: list artifacts
        run: ｜
          sudo apt install -y tree
          tree