name: go-flutter

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: britannio/action-install-flutter@v0.4
        with:
          version: 1.22.4

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.6
          stable: true
    
      - name: Print go env and version
        run: |
          go env -w GO111MODULE=on
          go env
          go version
  
      - name: Print flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

